# Stage 1: Build the Angular app
FROM node:18-alpine AS build


WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build --prod

# stage 2: SERVE with NGINX 

FROM nginx:alpine

COPY --from=build /app/dist/PortfolioApp /usr/share/nginx/html
COPY nginx.conf /etc/nginx